### ISSUE TITLE
Cannot reuse existing results from previous experiments

### ISSUE THREAD

**Issue by sun8608** [bioidiap/bob.bio.spear#3]
Sorry to interrupt again! I was trying to reuse results from previous experiments--the preprocessed data: 
sudo /usr/local/bin/verify_ivector.py -vv -d voxforge --skip-preprocessing --preprocessed-directory /usr/local/lib/python2.7/dist-packages/bob.db.voxforge-2.0.2-py2.7.egg/bob/db/voxforge/lists/preprocessed -e mfcc-60 -s ivector_test --groups {dev,eval} 
But the "--skip-preprocessing" seems not work and it still requires  me to put preprocessor, I follows instructions from the manual, please tell me where I am doing wrong here, thank you!

**Comment by laurentes** [comment]
As far as I remember (at least for the 'old' version of spear), you have to specify both the preprocessor and the --skip-preproccessing options to make things working. In this case, this won't be recomputed.

**Comment by siebenkopf** [comment]
Indeed, for technical reasons a preprocessor is required even if preprocessing is skipped. In fact, all elements of the tool chain (database, preprocessor, extractor and algorithm) are required to be specified on command line, in any case -- even if the according steps are skipped.

Maybe in future versions, we might provide options to deal with that, but for now, everything needs to be specified.
